//! Rule loading and match aggregation for the results view.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use super::eval::EventView;
use super::{evaluate_view, parse_rules, Rule};
use crate::model::NormalizedEvent;

// `SHIPPED_RULES: &[(file name, source)]`, generated by build.rs from
// `rules/*.yar`.
include!(concat!(env!("OUT_DIR"), "/shipped_rules.rs"));

/// A rule file that failed to parse. Only that file is disabled; the rest of
/// the set still loads (docs/04 "파싱 오류가 있는 룰은 해당 룰만 비활성").
#[derive(Debug, Clone)]
pub struct RuleError {
    pub path: PathBuf,
    pub message: String,
}

#[derive(Debug, Default)]
pub struct RuleSet {
    rules: Vec<Rule>,
    errors: Vec<RuleError>,
    /// Each rule's original text, so the editor can open a shipped rule
    /// that lives in a multi-rule file. Only files are sliced; a set built
    /// from a source string keeps nothing here.
    sources: BTreeMap<String, String>,
    /// Ids that came from the user directory in [`Self::load_layered`].
    user: BTreeSet<String>,
}

impl RuleSet {
    pub fn from_source(src: &str) -> Result<Self, super::ParseRuleError> {
        Ok(Self {
            rules: parse_rules(src)?,
            ..Self::default()
        })
    }

    /// A set holding one already-parsed rule, for evaluating it alone.
    pub fn single(rule: Rule) -> Self {
        Self {
            rules: vec![rule],
            ..Self::default()
        }
    }

    /// The rule pack compiled into the binary.
    pub fn shipped() -> Self {
        let mut set = Self::default();
        for (name, source) in SHIPPED_RULES {
            set.add_file(PathBuf::from(name), source);
        }
        set
    }

    /// Loads every `*.yar` file in a directory. Other files are ignored.
    pub fn load_dir(dir: &Path) -> std::io::Result<Self> {
        let mut set = Self::default();
        let mut paths: Vec<PathBuf> = std::fs::read_dir(dir)?
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .filter(|path| path.extension().is_some_and(|ext| ext == "yar"))
            .collect();
        // Deterministic order so rule precedence and reports are reproducible.
        paths.sort();

        for path in paths {
            match std::fs::read_to_string(&path) {
                Ok(source) => set.add_file(path, &source),
                Err(e) => set.errors.push(RuleError {
                    path,
                    message: e.to_string(),
                }),
            }
        }

        Ok(set)
    }

    /// Parses one rule file's text; a file that fails only disables itself.
    fn add_file(&mut self, path: PathBuf, source: &str) {
        match parse_rules(source) {
            Ok(rules) => {
                // Slicing cannot fail once the source parsed.
                for (id, text) in super::rule_sources(source).unwrap_or_default() {
                    self.sources.insert(id, text);
                }
                self.rules.extend(rules);
            }
            Err(e) => self.errors.push(RuleError {
                path,
                message: e.to_string(),
            }),
        }
    }

    /// The shipped pack, then user rules from `user_dir` (absent is fine),
    /// where a user rule replaces a shipped rule with the same id.
    pub fn load_layered(user_dir: &Path) -> std::io::Result<Self> {
        let mut set = Self::shipped();

        if user_dir.is_dir() {
            let user = Self::load_dir(user_dir)?;
            for rule in user.rules {
                set.user.insert(rule.id.clone());
                match set.rules.iter_mut().find(|existing| existing.id == rule.id) {
                    Some(existing) => *existing = rule,
                    None => set.rules.push(rule),
                }
            }
            set.sources.extend(user.sources);
            set.errors.extend(user.errors);
        }

        Ok(set)
    }

    /// Writes the shipped pack and copies the user rule files into the case
    /// so a result can be explained later even if the rules change (docs/07
    /// `cases/<id>/rules/`).
    pub fn snapshot_into(user_dir: &Path, case_rules_dir: &Path) -> std::io::Result<usize> {
        std::fs::create_dir_all(case_rules_dir)?;
        let mut written = Vec::new();

        for (name, source) in SHIPPED_RULES {
            std::fs::write(case_rules_dir.join(name), source)?;
            written.push((*name).to_owned());
        }
        if user_dir.is_dir() {
            for entry in std::fs::read_dir(user_dir)?.filter_map(Result::ok) {
                let path = entry.path();
                if path.extension().is_some_and(|ext| ext == "yar") {
                    let name = path.file_name().expect("file has a name").to_string_lossy();
                    // Prefixed so a user file cannot overwrite a shipped one.
                    let target = format!("user-{name}");
                    std::fs::copy(&path, case_rules_dir.join(&target))?;
                    written.push(target);
                }
            }
        }

        // The snapshot is a replacement, not an accumulation: a rule file left
        // behind from an earlier run would keep claiming it was applied to
        // results it no longer contributed to.
        for entry in std::fs::read_dir(case_rules_dir)?.filter_map(Result::ok) {
            let path = entry.path();
            let stale = path.extension().is_some_and(|ext| ext == "yar")
                && !path
                    .file_name()
                    .is_some_and(|name| written.iter().any(|kept| kept.as_str() == name));
            if stale {
                std::fs::remove_file(&path)?;
            }
        }

        Ok(written.len())
    }

    pub fn rules(&self) -> &[Rule] {
        &self.rules
    }

    pub fn rule(&self, id: &str) -> Option<&Rule> {
        self.rules.iter().find(|r| r.id == id)
    }

    /// The rule's original text, when the set was loaded from files.
    pub fn source(&self, id: &str) -> Option<&str> {
        self.sources.get(id).map(String::as_str)
    }

    /// Whether the effective rule came from the user directory.
    pub fn is_user(&self, id: &str) -> bool {
        self.user.contains(id)
    }

    pub fn errors(&self) -> &[RuleError] {
        &self.errors
    }

    /// Rules whose `meta: log_type` allows this log type.
    pub fn for_log_type<'a>(&'a self, log_type: &'a str) -> impl Iterator<Item = &'a Rule> {
        self.rules.iter().filter(move |r| r.applies_to(log_type))
    }
}

/// One event that a rule fired on, with the evidence.
#[derive(Debug, Clone)]
pub struct Hit {
    pub event_id: u64,
    pub matched_fields: BTreeMap<String, String>,
}

/// Matches grouped by rule, as the results view renders them.
#[derive(Debug, Clone)]
pub struct RuleMatchGroup {
    pub rule_id: String,
    pub severity: String,
    pub description: String,
    pub matches: Vec<Hit>,
}

#[derive(Debug, Clone, Default)]
pub struct MatchReport {
    pub groups: Vec<RuleMatchGroup>,
    /// Events no rule matched. `matched + unmatched == total` must hold so a
    /// silent gap in coverage is visible (docs/04).
    pub unmatched: u64,
    pub total: u64,
}

/// Per-rule totals kept while streaming; bounded by the number of rules.
#[derive(Debug, Clone)]
pub struct RuleSummary {
    pub rule_id: String,
    pub severity: String,
    pub description: String,
    pub match_count: u64,
}

#[derive(Debug, Clone, Default)]
pub struct MatchSummary {
    pub rules: Vec<RuleSummary>,
    pub unmatched: u64,
    pub total: u64,
}

/// Incremental evaluator for callback-style event sources.
///
/// `Store::for_each_event` hands events over one at a time, so there is no
/// iterator to feed [`stream_matches`]. Using this keeps both sides streaming:
/// events are never collected, and hits leave in bounded batches (NFR-2).
pub struct MatchStreamer<'a> {
    set: &'a RuleSet,
    batch_size: usize,
    batch: Vec<(String, Hit)>,
    counts: BTreeMap<String, u64>,
    summary: MatchSummary,
    /// First sink failure; reported by `finish`.
    error: Option<String>,
}

impl<'a> MatchStreamer<'a> {
    pub fn new(set: &'a RuleSet, batch_size: usize) -> Self {
        Self {
            set,
            batch_size,
            batch: Vec::with_capacity(batch_size.min(4096)),
            counts: BTreeMap::new(),
            summary: MatchSummary::default(),
            error: None,
        }
    }

    /// Evaluates every rule against one event, flushing when the batch fills.
    pub fn push<E: std::fmt::Display>(
        &mut self,
        event_id: u64,
        event: &NormalizedEvent,
        sink: &mut impl FnMut(&[(String, Hit)]) -> Result<(), E>,
    ) {
        self.push_matching(event_id, event, sink, |_| true);
    }

    /// Evaluates only rules whose `meta.log_type` accepts this event's type.
    pub fn push_for_log_type<E: std::fmt::Display>(
        &mut self,
        event_id: u64,
        log_type: &str,
        event: &NormalizedEvent,
        sink: &mut impl FnMut(&[(String, Hit)]) -> Result<(), E>,
    ) {
        self.push_matching(event_id, event, sink, |rule| rule.applies_to(log_type));
    }

    fn push_matching<E: std::fmt::Display>(
        &mut self,
        event_id: u64,
        event: &NormalizedEvent,
        sink: &mut impl FnMut(&[(String, Hit)]) -> Result<(), E>,
        applies: impl Fn(&Rule) -> bool,
    ) {
        self.summary.total += 1;
        let view = EventView::new(event);
        let mut hit_any = false;

        for rule in &self.set.rules {
            if !applies(rule) {
                continue;
            }
            let Some(matched) = evaluate_view(rule, &view) else {
                continue;
            };
            hit_any = true;
            *self.counts.entry(rule.id.clone()).or_default() += 1;
            self.batch.push((
                rule.id.clone(),
                Hit {
                    event_id,
                    matched_fields: matched.matched_fields,
                },
            ));
        }

        if !hit_any {
            self.summary.unmatched += 1;
        }
        if self.batch.len() >= self.batch_size {
            self.flush(sink);
        }
    }

    fn flush<E: std::fmt::Display>(
        &mut self,
        sink: &mut impl FnMut(&[(String, Hit)]) -> Result<(), E>,
    ) {
        if self.batch.is_empty() {
            return;
        }
        if let Err(e) = sink(&self.batch) {
            self.error.get_or_insert_with(|| e.to_string());
        }
        self.batch.clear();
    }

    /// Flushes the tail and returns the summary, or the first sink failure.
    pub fn finish<E: std::fmt::Display>(
        mut self,
        sink: &mut impl FnMut(&[(String, Hit)]) -> Result<(), E>,
    ) -> Result<MatchSummary, String> {
        self.flush(sink);
        if let Some(error) = self.error {
            return Err(error);
        }
        self.summary.rules = self
            .set
            .rules
            .iter()
            .filter_map(|rule| {
                self.counts.get(&rule.id).map(|count| RuleSummary {
                    rule_id: rule.id.clone(),
                    severity: rule.severity().to_string(),
                    description: rule.description().to_string(),
                    match_count: *count,
                })
            })
            .collect();
        Ok(self.summary)
    }
}

/// Streams matches to `sink` in batches instead of collecting them all.
///
/// A broad rule over tens of millions of events yields millions of hits, each
/// carrying `matched_fields`; holding them would break NFR-2. Only per-rule
/// counters stay in memory.
pub fn stream_matches<'a, I, E>(
    set: &RuleSet,
    events: I,
    batch_size: usize,
    mut sink: impl FnMut(&[(String, Hit)]) -> Result<(), E>,
) -> Result<MatchSummary, E>
where
    I: IntoIterator<Item = (u64, &'a NormalizedEvent)>,
{
    let mut summary = MatchSummary::default();
    let mut counts: BTreeMap<&str, u64> = BTreeMap::new();
    let mut batch: Vec<(String, Hit)> = Vec::with_capacity(batch_size.min(4096));

    for (event_id, event) in events {
        summary.total += 1;
        let view = EventView::new(event);
        let mut hit_any = false;

        for rule in &set.rules {
            let Some(matched) = evaluate_view(rule, &view) else {
                continue;
            };
            hit_any = true;
            *counts.entry(rule.id.as_str()).or_default() += 1;
            batch.push((
                rule.id.clone(),
                Hit {
                    event_id,
                    matched_fields: matched.matched_fields,
                },
            ));
            if batch.len() >= batch_size {
                sink(&batch)?;
                batch.clear();
            }
        }

        if !hit_any {
            summary.unmatched += 1;
        }
    }

    if !batch.is_empty() {
        sink(&batch)?;
    }

    summary.rules = set
        .rules
        .iter()
        .filter_map(|rule| {
            counts.get(rule.id.as_str()).map(|count| RuleSummary {
                rule_id: rule.id.clone(),
                severity: rule.severity().to_string(),
                description: rule.description().to_string(),
                match_count: *count,
            })
        })
        .collect();

    Ok(summary)
}

/// Collects every match in memory. Suitable for tests and small inputs;
/// production paths use [`stream_matches`].
pub fn match_events<'a, I>(set: &RuleSet, events: I) -> MatchReport
where
    I: IntoIterator<Item = (u64, &'a NormalizedEvent)>,
{
    let mut groups: BTreeMap<&str, RuleMatchGroup> = BTreeMap::new();
    let mut report = MatchReport::default();

    for (event_id, event) in events {
        report.total += 1;
        let mut hit_any = false;
        // One view per event: JSON columns are parsed at most once for all rules.
        let view = EventView::new(event);

        for rule in &set.rules {
            let Some(matched) = evaluate_view(rule, &view) else {
                continue;
            };
            hit_any = true;
            groups
                .entry(rule.id.as_str())
                .or_insert_with(|| RuleMatchGroup {
                    rule_id: rule.id.clone(),
                    severity: rule.severity().to_string(),
                    description: rule.description().to_string(),
                    matches: Vec::new(),
                })
                .matches
                .push(Hit {
                    event_id,
                    matched_fields: matched.matched_fields,
                });
        }

        if !hit_any {
            report.unmatched += 1;
        }
    }

    report.groups = groups.into_values().collect();
    report
}
