//! Portable case-root resolution. Everything the app writes lives under
//! `<base>/cases/`; never AppData or other per-user system directories.
//! See docs/07-case-layout.md.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use time::PrimitiveDateTime;

const CASES_DIR: &str = "cases";

/// Candidate roots, highest priority first.
#[derive(Debug, Clone, Copy)]
pub struct RootSources<'a> {
    /// `AWSLOG_CASES_DIR`
    pub env_dir: Option<&'a Path>,
    /// `--cases-dir`
    pub cli_dir: Option<&'a Path>,
    /// Directory containing the executable.
    pub exe_dir: &'a Path,
}

#[derive(Debug, thiserror::Error)]
pub enum PathError {
    #[error("cases directory is not writable: {path} ({source})")]
    NotWritable {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("failed to create case directory: {path} ({source})")]
    CaseCreate {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
}

/// Applies the documented priority: env var, then CLI flag, then `cases/`
/// beside the executable. Pure: performs no filesystem access.
pub fn resolve(sources: &RootSources<'_>) -> PathBuf {
    if let Some(dir) = sources.env_dir {
        return dir.to_path_buf();
    }
    if let Some(dir) = sources.cli_dir {
        return dir.to_path_buf();
    }
    portable_base_dir(sources.exe_dir).join(CASES_DIR)
}

/// Base directory for portable output. On macOS the executable sits in
/// `Foo.app/Contents/MacOS`, so output belongs beside the bundle, not inside it.
pub fn portable_base_dir(exe_dir: &Path) -> &Path {
    let mut components = exe_dir.iter().rev();
    let is_bundle_exe = components.next().is_some_and(|c| c == "MacOS")
        && components.next().is_some_and(|c| c == "Contents")
        && components
            .next()
            .is_some_and(|c| Path::new(c).extension().is_some_and(|e| e == "app"));

    if is_bundle_exe {
        // Strip MacOS/Contents/Foo.app.
        exe_dir
            .ancestors()
            .nth(3)
            .expect("bundle layout has three parents")
    } else {
        exe_dir
    }
}

/// Rejects a case id that could escape the cases root. Ids are generated by
/// `create_case`, but they arrive back from the UI as plain strings.
pub fn is_safe_case_id(case_id: &str) -> bool {
    !case_id.is_empty()
        && case_id.len() <= 128
        && case_id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// A verified, writable cases root.
#[derive(Debug, Clone)]
pub struct CasesRoot(PathBuf);

/// Creates the cases root if needed and proves it is writable.
/// Never falls back to a system directory: a failure here is reported to the user.
pub fn prepare(root: &Path) -> Result<CasesRoot, PathError> {
    let fail = |source: io::Error| PathError::NotWritable {
        path: root.to_path_buf(),
        source,
    };

    fs::create_dir_all(root).map_err(fail)?;

    // create_dir_all succeeds on an existing read-only dir, so probe explicitly.
    let probe = root.join(".write-probe");
    fs::write(&probe, b"").map_err(fail)?;
    let _ = fs::remove_file(&probe);

    Ok(CasesRoot(root.to_path_buf()))
}

impl CasesRoot {
    pub fn path(&self) -> &Path {
        &self.0
    }

    /// Directory for one case, refusing ids that are not self-generated.
    pub fn case_dir(&self, case_id: &str) -> Option<PathBuf> {
        is_safe_case_id(case_id).then(|| self.0.join(case_id))
    }

    /// User rule files, beside the cases (docs/04 "룰 파일 배치"). Not a
    /// case: `list_cases` only counts directories holding a `case.json`.
    pub fn user_rules_dir(&self) -> PathBuf {
        self.0.join("rules")
    }

    /// Removes one case and everything under it. The id is validated first:
    /// a recursive delete driven by an unchecked string is how a traversal
    /// bug becomes evidence loss.
    pub fn delete_case(&self, case_id: &str) -> std::io::Result<()> {
        let dir = self.case_dir(case_id).ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                format!("unsafe case id: {case_id}"),
            )
        })?;
        // Only delete something this tool created. An interrupted delete can
        // leave any subset behind, so any one marker is enough — requiring
        // case.json would strand half-deleted cases, which `list_cases`
        // already hides.
        const MARKERS: [&str; 4] = ["case.json", "session.duckdb", "rules", "logs"];
        if !MARKERS.iter().any(|m| dir.join(m).exists()) {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                format!("not a case directory: {case_id}"),
            ));
        }
        std::fs::remove_dir_all(dir)
    }

    /// Summaries of every case on disk, newest first, read from `case.json`
    /// only — the databases stay closed (docs/07).
    pub fn list_cases(&self) -> std::io::Result<Vec<String>> {
        let mut ids: Vec<String> = std::fs::read_dir(&self.0)?
            .filter_map(Result::ok)
            .filter(|entry| entry.path().join("case.json").is_file())
            .filter_map(|entry| entry.file_name().into_string().ok())
            .collect();
        // Ids start with a timestamp, so reverse lexical order is newest first.
        ids.sort_unstable_by(|a, b| b.cmp(a));
        Ok(ids)
    }

    /// Creates `cases/<yyyymmdd-HHMMSS-slug>/` with its fixed subdirectories.
    /// A numeric suffix keeps two cases started in the same second distinct.
    pub fn create_case(
        &self,
        input_dir: &Path,
        started_at: PrimitiveDateTime,
    ) -> Result<CaseDir, PathError> {
        let stamp = format!(
            "{:04}{:02}{:02}-{:02}{:02}{:02}",
            started_at.year(),
            u8::from(started_at.month()),
            started_at.day(),
            started_at.hour(),
            started_at.minute(),
            started_at.second()
        );
        let slug = slugify(input_dir);

        let mut id = format!("{stamp}-{slug}");
        let mut dir = self.0.join(&id);
        for n in 2..1000 {
            if !dir.exists() {
                break;
            }
            id = format!("{stamp}-{slug}-{n}");
            dir = self.0.join(&id);
        }

        for sub in ["rules", "exports", "logs"] {
            fs::create_dir_all(dir.join(sub)).map_err(|source| PathError::CaseCreate {
                path: dir.clone(),
                source,
            })?;
        }

        Ok(CaseDir { id, dir })
    }
}

/// One analysis case on disk.
#[derive(Debug, Clone)]
pub struct CaseDir {
    id: String,
    dir: PathBuf,
}

impl CaseDir {
    pub fn id(&self) -> &str {
        &self.id
    }

    pub fn dir(&self) -> &Path {
        &self.dir
    }

    pub fn session_db(&self) -> PathBuf {
        self.dir.join("session.duckdb")
    }

    pub fn logs_dir(&self) -> PathBuf {
        self.dir.join("logs")
    }

    pub fn rules_dir(&self) -> PathBuf {
        self.dir.join("rules")
    }
}

/// Lowercase ASCII slug of the input directory name; unsafe characters collapse
/// into single hyphens so the case id stays path-safe on every platform.
fn slugify(input_dir: &Path) -> String {
    let name = input_dir
        .file_name()
        .map(|n| n.to_string_lossy().to_ascii_lowercase())
        .unwrap_or_default();

    let mut slug = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch);
        } else if !slug.ends_with('-') {
            slug.push('-');
        }
    }
    let trimmed = slug.trim_matches('-');
    if trimmed.is_empty() {
        "case".to_string()
    } else {
        trimmed.to_string()
    }
}
