// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	casesRoot: () => __TAURI_INVOKE<string>("cases_root"),
	/**
	 *  FR-2: list supported gzip log candidates without reading their contents.
	 *  Async so Tauri runs it off the main thread — a bucket export can hold tens
	 *  of thousands of files and the walk must not freeze the window (NFR-3).
	 */
	scanDirectory: (path: string) => typedError<ScanSummary, string>(__TAURI_INVOKE("scan_directory", { path })),
	/**
	 *  FR-3/FR-4: classify each candidate and return one sample record per file.
	 *  Files are decoded in parallel; progress is emitted so the UI can show
	 *  movement instead of waiting for one large response.
	 */
	detectLogs: (path: string) => typedError<DetectionRow[], string>(__TAURI_INVOKE("detect_logs", { path })),
	/**
	 *  FR-5: create a case and parse the directory into its session database.
	 *  Cancellation is cooperative; partial results stay on disk.
	 */
	startParse: (path: string, selected: string[], mapping: MappingEntry[]) => typedError<ParseResult, string>(__TAURI_INVOKE("start_parse", { path, selected, mapping })),
	/**  Cooperative cancel: the parse loop checks this between files and batches. */
	cancelParse: () => __TAURI_INVOKE<void>("cancel_parse"),
	/**
	 *  Lists rule groups and totals for a case. The window's log type and date
	 *  range narrow everything, group counts included; its search is ignored.
	 *  Rows are paged by `query_rule_matches` and `query_events`, so scrolling
	 *  never repeats the case-level scans this does.
	 */
	queryResults: (caseId: string, window: Window) => typedError<ResultPage, string>(__TAURI_INVOKE("query_results", { caseId, window })),
	/**
	 *  One page of a rule's matches. Served from the match table alone, so a
	 *  page costs the same on a 300M-event case as on a small one.
	 */
	queryRuleMatches: (caseId: string, ruleId: string, window: Window) => typedError<EventPage, string>(__TAURI_INVOKE("query_rule_matches", { caseId, ruleId, window })),
	/**
	 *  The payload paths a case's events hold (`request.*`, `response.*`,
	 *  `resources.*`), counted while parsing, so the rule editor can offer what
	 *  the data has instead of a fixed field list. `log_type` narrows to the
	 *  tab being looked at.
	 */
	listPayloadKeys: (caseId: string, logType: string | null) => typedError<PayloadKey[], string>(__TAURI_INVOKE("list_payload_keys", { caseId, logType })),
	/**
	 *  FR-4: the head of one detected file as pieces with the column each one
	 *  feeds, under the editor's current mapping (docs/03 "포맷 카드").
	 *  `display_path` is the detection row's path, relative to `root`.
	 */
	previewHead: (root: string, displayPath: string, logType: string, mapping: MappingEntry[]) => typedError<HeadPreview, string>(__TAURI_INVOKE("preview_head", { root, displayPath, logType, mapping })),
	/**  Fetches one original record on demand (never in list payloads). */
	getRawRecord: (caseId: string, eventId: number | null) => typedError<string | null, string>(__TAURI_INVOKE("get_raw_record", { caseId, eventId })),
	/**
	 *  Past cases, newest first. Reads `case.json` only so the list is cheap
	 *  even with many cases (docs/07).
	 */
	listCases: () => typedError<CaseSummary[], string>(__TAURI_INVOKE("list_cases")),
	/**
	 *  FR-6: drop a case and its database from disk. Irreversible, so the UI
	 *  confirms first; the id is validated inside `delete_case`.
	 */
	deleteCase: (caseId: string) => typedError<null, string>(__TAURI_INVOKE("delete_case", { caseId })),
	/**  The mapping the editor starts from, so the UI never hard-codes AWS paths. */
	defaultMapping: () => __TAURI_INVOKE<MappingEntry[]>("default_mapping"),
	/**
	 *  Resolves a mapping against one sample record. The editor previews through
	 *  the same resolver the parser uses, so what is shown is what gets stored.
	 */
	previewMapping: (record: string, mapping: MappingEntry[]) => typedError<FieldPreview[], string>(__TAURI_INVOKE("preview_mapping", { record, mapping })),
	/**  Every effective rule's text, so the editor can open any of them. */
	listRuleSources: () => typedError<RuleSource[], string>(__TAURI_INVOKE("list_rule_sources")),
	/**
	 *  Runs one rule over the case and stores its matches. Holds the parse
	 *  slot: it writes to the same database a parse would.
	 */
	evaluateRule: (caseId: string, ruleId: string) => typedError<number, string>(__TAURI_INVOKE("evaluate_rule", { caseId, ruleId })),
	/**
	 *  Validates and stores one user rule, refreshes the case snapshot and
	 *  registers the rule as pending in the case: selecting it evaluates it.
	 */
	saveRule: (caseId: string, source: string) => typedError<string, string>(__TAURI_INVOKE("save_rule", { caseId, source })),
	/**
	 *  Removes a rule from this case. A user rule's file goes too (the shipped
	 *  rule it overrode, if any, is back for the next case); a shipped rule
	 *  stays in the pack and only leaves this case's results.
	 */
	deleteRule: (caseId: string, ruleId: string) => typedError<null, string>(__TAURI_INVOKE("delete_rule", { caseId, ruleId })),
	/**
	 *  Pages every event, rule or not. This is how an analyst inspects what the
	 *  rules did not catch.
	 */
	queryEvents: (caseId: string, window: Window) => typedError<EventPage, string>(__TAURI_INVOKE("query_events", { caseId, window })),
	/**
	 *  One event's stored columns, for the detail view. Reads the row the rules
	 *  were evaluated against instead of re-resolving the raw record with the
	 *  mapping currently in the editor.
	 */
	getEvent: (caseId: string, eventId: number | null) => typedError<FieldPreview[], string>(__TAURI_INVOKE("get_event", { caseId, eventId })),
	explainRule: (source: string) => typedError<RuleOutline, RuleProblem>(__TAURI_INVOKE("explain_rule", { source })),
	/**
	 *  Events a draft rule would match, without saving it or disturbing the
	 *  case's recorded matches.
	 */
	countRuleMatches: (caseId: string, source: string) => typedError<RuleHits, string>(__TAURI_INVOKE("count_rule_matches", { caseId, source })),
};

/** Events */
export const events = {
	detectProgress: makeEvent<DetectProgress>("detect-progress"),
	parseProgress: makeEvent<ParseProgress>("parse-progress"),
};

/* Types */
export type CandidateRow = {
	display_path: string,
	size_bytes: number | null,
};

/**  One row of the case list. */
export type CaseSummary = {
	case_id: string,
	input_dir: string,
	status: string,
	event_count: number,
};

/**  Progress while classifying candidates. */
export type DetectProgress = {
	done: number,
	total: number,
};

export type DetectionRow = {
	display_path: string,
	log_type: string,
	confidence: string,
	record_count_estimate: number | null,
	estimated: boolean,
	members_in_head: number,
	sample: SampleRow | null,
	note: string | null,
};

/**  One page of rows, with the total that page was drawn from. */
export type EventPage = {
	rows: MatchRow[],
	/**
	 *  Rows matching the filter. Paging needs this, or the list stops short
	 *  of the filtered set or asks for pages that do not exist.
	 */
	total: number,
};

/**  One resolved field: `None` means no source path matched. */
export type FieldPreview = {
	field: string,
	label: string,
	value: string | null,
};

export type HeadPreview = {
	/**  Records found in the head, up to [`HEAD_RECORDS`]. */
	records: number,
	/**  Of those, records with both a time and an event name. */
	mapped: number,
	/**
	 *  Event names (ALB: HTTP methods; WAF: actions) in the head, most
	 *  frequent first.
	 */
	event_names: NameCount[],
	pieces: Piece[],
	/**
	 *  Every leaf path across the head with the records that had it, so the
	 *  UI can list what the first record happens to lack.
	 */
	paths: NameCount[],
	/**
	 *  Whether labels can be moved: only CloudTrail goes through the
	 *  editable mapping; the other producers have fixed normalizers.
	 */
	editable: boolean,
};

/**  Parsed events per log type, for the type tabs. */
export type LogTypeCount = {
	log_type: string,
	events: number,
};

/**
 *  One row of the mapping editor: a column, its display name and the JSON
 *  paths feeding it. `label` travels with the row so the UI never keeps its
 *  own copy of the names — see `Field::label`.
 */
export type MappingEntry = {
	field: string,
	label: string,
	sources: string[],
};

/**  One matched event, summarized. The raw record is fetched separately. */
export type MatchRow = {
	event_id: number | null,
	event_time: string | null,
	event_name: string | null,
	event_source: string | null,
	identity_arn: string | null,
	source_ip: string | null,
	/**  `files.log_type` of the event's source file; picks the column set. */
	log_type: string,
	user_agent: string | null,
	aws_region: string | null,
	error_code: string | null,
	/**  CloudTrail only: ARN of the first entry in `resources`. */
	resource: string | null,
	/**  ALB only: `request.url`, `response.elb_status_code`, `resources.target`. */
	url: string | null,
	status: string | null,
	target: string | null,
	/**  WAF only: request origin country and the rule that decided the action. */
	country: string | null,
	rule: string | null,
	/**
	 *  HTTP method from the request body; `event_name` already carries it
	 *  for HTTP producers, but WAF puts the action there instead.
	 */
	method: string | null,
	/**  JSON object of `$var` to the value that satisfied it (docs/04). */
	matched_fields: string,
};

/**  A name and how many head records carried it. */
export type NameCount = {
	name: string,
	count: number,
};

/**  Progress while parsing into the session store. */
export type ParseProgress = {
	files_done: number,
	files_total: number,
	records_parsed: number,
	/**
	 *  True once cancellation was requested, so the UI can lock the button
	 *  instead of firing the command repeatedly.
	 */
	cancel_requested: boolean,
};

/**  Result of one parse run, shown when it finishes. */
export type ParseResult = {
	case_id: string,
	files_parsed: number,
	files_skipped: number,
	files_failed: number,
	records_parsed: number,
	cancelled: boolean,
};

/**
 *  One JSON path seen inside a payload column while parsing, and how many
 *  events of that log type carried it (docs/04 "페이로드 키").
 */
export type PayloadKey = {
	log_type: string,
	/**  As a rule spells it: `request.bucketName`, `resources.0.ARN`. */
	path: string,
	events: number,
};

/**
 *  One piece of the first record: a leaf path (or, for ALB, a token
 *  position) and its value, with the column it feeds.
 */
export type Piece = {
	path: string,
	value: string,
	/**  `event_name`, `request.bucketName`, … ; `None` when nothing reads it. */
	field: string | null,
	/**
	 *  What to print above the piece: the built-in field's display name or
	 *  the rule path.
	 */
	label: string | null,
};

/**
 *  The results sidebar: type tabs, date bounds, rule groups and the case
 *  totals under the window's scope. Rows are paged separately
 *  ([`rule_matches`], [`all_events`]) so scrolling never recomputes these.
 */
export type ResultPage = {
	/**
	 *  Every type in the case, unaffected by the window's type filter so the
	 *  tabs stay stable while one is selected.
	 */
	log_types: LogTypeCount[],
	/**
	 *  First and last event day in KST across the whole case; bounds for
	 *  the date filter. `None` when the case has no timed event.
	 */
	first_day: string | null,
	last_day: string | null,
	groups: RuleGroup[],
	total_events: number,
	matched_events: number,
	/**  Events no rule matched. Shown so a coverage gap is visible, not hidden. */
	unmatched_events: number,
};

export type RuleGroup = {
	rule_id: string,
	/**  `meta: name`, or the id when the rule has none. */
	name: string,
	severity: string,
	description: string,
	match_count: number,
	/**
	 *  False until the rule has been run over this case; `match_count` is
	 *  meaningless before that.
	 */
	evaluated: boolean,
};

/**
 *  A trial run's result: matches out of everything scanned, so the editor can
 *  show the hit count as a proportion instead of a bare number.
 */
export type RuleHits = {
	hits: number,
	total: number,
};

/**
 *  What a draft rule says, in words, plus its id and metadata. The editor
 *  shows this beside the source so intent can be checked without re-reading
 *  the syntax.
 */
export type RuleOutline = {
	rule_id: string,
	/**  `meta: name`, or the id when the draft has none. */
	name: string,
	description: string,
	severity: string,
	/**  The condition rendered as a sentence. */
	explanation: string,
};

/**
 *  Why a draft does not parse, and where. `line` is what the editor marks
 *  in the gutter; it is absent for errors that are not a place in the text
 *  (a duplicate id, two rules in one draft).
 */
export type RuleProblem = {
	message: string,
	line: number | null,
};

/**
 *  One effective rule's text. Saving any rule writes a user rule, which
 *  overrides a shipped rule with the same id (docs/04 rule layering).
 */
export type RuleSource = {
	rule_id: string,
	source: string,
	/**  Came from `cases/rules/`: deleting it removes the file too. */
	user: boolean,
};

export type SampleRow = {
	raw: string | null,
	event_time: string | null,
	event_source: string | null,
	event_name: string | null,
	aws_region: string | null,
	user_identity_type: string | null,
	user_identity_arn: string | null,
	source_ip_address: string | null,
};

export type ScanSummary = {
	root: string,
	candidate_count: number,
	total_bytes: number | null,
	candidates: CandidateRow[],
	skipped: SkippedRow[],
};

export type SkipKind = "extension" | "empty" | "unreadable";

export type SkippedRow = {
	display_path: string,
	kind: SkipKind,
};

/**
 *  One page of rows: which slice, filtered how, ordered how. Crosses IPC as
 *  one object so the commands do not grow a parameter per filter.
 */
export type Window = {
	offset: number,
	limit: number,
	/**
	 *  Case-insensitive substring over the columns the table shows. Empty
	 *  matches everything. Searching hidden columns would return rows whose
	 *  reason for matching is invisible.
	 */
	search: string,
	/**  Oldest first by default: an incident is read forwards in time. */
	newest_first: boolean,
	/**
	 *  Restrict to events from files of this `files.log_type`; `None` is
	 *  every type. Drives the type tabs.
	 */
	log_type: string | null,
	/**
	 *  Inclusive KST day bounds, `YYYY-MM-DD`. Applied above every other
	 *  filter: rule counts, event list and matches all honour them.
	 */
	from: string | null,
	to: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

